name: personalloan

networks:
  personalloan-network:

volumes:
  personalloan-postgres-data:
  personalloan-redis-data:
  personalloan-mssql-data:
  personalloan-mongo-data:
  personalloan-frontend-data:
  personalloan-backend-data:
  personalloan-agent-data:
  personalloan-workflow-data:

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "15432:5432"
    volumes:
      - personalloan-postgres-data:/var/lib/postgresql/data
    networks:
      - personalloan-network
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "16379:6379"
    volumes:
      - personalloan-redis-data:/data
    networks:
      - personalloan-network
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - personalloan-mongo-data:/data/db
    networks:
      - personalloan-network
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "11433:1433"
    volumes:
      - personalloan-mssql-data:/var/opt/mssql
    networks:
      - personalloan-network
  temporal:
    image: temporalio/auto-setup:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "17233:7233"
      - "18080:8080"
    depends_on:
      - postgres
    networks:
      - personalloan-network
  aiagent-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    ports:
      - "13000:3000"
    networks:
      - personalloan-network
    env_file:
      - .env
    volumes:
      - personalloan-frontend-data:/app/data
  aiagent-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    ports:
      - "18000:8000"
    networks:
      - personalloan-network
    env_file:
      - .env
    depends_on:
      - mongodb
      - aiagent-agent
    volumes:
      - personalloan-backend-data:/app/data
  aiagent-agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    restart: unless-stopped
    networks:
      - personalloan-network
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - personalloan-agent-data:/app/data

  aiagent-workflow:
    build:
      context: .
      dockerfile: workflow/Dockerfile
    restart: unless-stopped
    networks:
      - personalloan-network
    env_file:
      - .env
    depends_on:
      - temporal
    volumes:
      - personalloan-workflow-data:/app/data
